version: '3'

services:
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    restart: always

  app:
    container_name: app
    build:
      context: .
    ports:
      - 4000:4000
    env_file:
      - .dev.env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    depends_on:
      - mongodb
    restart: always

volumes:
  data:
