version: '3'

services:
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
      - ./src/config/db.entry.sh:/db.entry.sh
    restart: always

volumes:
  data:
